(function () {
  "use strict";
  const A=window.Atlas=window.Atlas||{};
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const section=(eyebrow,title,text="")=>`<header class="polish-section-head"><span>${esc(eyebrow)}</span><h2>${esc(title)}</h2>${text?`<p>${esc(text)}</p>`:""}</header>`;
  function renderOpusDei(){
    const prep=A.data.libraryMap.get("preparadora-circulos"), sjm=A.data.libraryMap.get("san-josemaria"), unlocked=A.storage.isFeatureUnlocked("preparadora-circulos");
    const latest=(window.ATLAS_EXTERNAL?.items||[]).filter(item=>item.source==="Opus Dei").slice(0,2);
    const corpus=(prep?.documents||[]).filter(doc=>!/Francisco|León|Leon|Papa|Vaticano|Catecismo|Concilio/i.test(`${doc.author||""} ${doc.title||""}`));
    const authors=[...new Map(corpus.map(doc=>[doc.author||doc.category||"Otros recursos",(corpus.filter(item=>(item.author||item.category||"Otros recursos") === (doc.author||doc.category||"Otros recursos")))] )).entries()].slice(0,7);
    const foundations=["San Josemaría · obras, tertulias y El Fundador","Don Álvaro · obras y textos","Don Javier · obras y textos","Don Fernando · obras y textos","Romana","Meditaciones"];
    const methods=[["Modo 1","Temas: doctrina · norma · lucha","Esquema breve con fuentes, hilo conductor y aplicaciones."],["Modo 2","Temas + Evangelio del día","Meditación y círculo completo conectados con el Evangelio."]];
    return `<section class="page atlas-v7 v7-opus opus-polished"><header><span>Recursos reunidos</span><h1>Opus Dei</h1><p>Oración, formación y fuentes en un solo lugar.</p></header><section class="v7-opus-lead"><div><span>San Josemaría</span><h2>Encontrar a Dios en la vida ordinaria.</h2><p>Obras, textos, oración y recursos para vivir la fe hoy.</p><div><a href="#/library/san-josemaria/documents">Abrir biblioteca</a><a href="#/spiritual/escriva">Escriva.org</a></div></div><a href="${esc(sjm?.notebookUrl||"#/library/san-josemaria/documents")}" ${sjm?.notebookUrl?`target="_blank" rel="noopener"`:""}><small>Especialista</small><b>Preguntar a San Josemaría ↗</b></a></section><section class="opus-prep-card">${section("Preparador de Círculos","Prepara con fuentes. Después, hazlo tuyo.","Una ayuda para estudiar y preparar; no sustituye la preparación personal del formador.")}<div class="opus-foundations">${foundations.map((item,index)=>`<span><i>${String(index+1).padStart(2,"0")}</i>${esc(item)}</span>`).join("")}</div><div class="opus-modes">${methods.map(([mark,title,text])=>`<article><b>${mark}</b><h3>${title}</h3><p>${text}</p></article>`).join("")}</div><div class="button-row">${unlocked?`<a class="primary-button" href="${esc(prep?.notebookUrl||"")}" target="_blank" rel="noopener">Abrir Preparador de Círculos ↗</a><a class="secondary-button" href="#/library/preparadora-circulos/documents">Ver corpus</a>`:`<a class="secondary-button" href="#/mi-atlas">Desbloquear en Mi Atlas</a>`}</div></section><section class="opus-corpus">${section("Corpus disponible",`${corpus.length} recursos para formación y círculos`,"Explora por autor o por obra. Los textos pontificios se consultan en sus bibliotecas especializadas.")}<div class="opus-corpus-grid">${authors.map(([author,docs])=>`<details><summary><b>${esc(author)}</b><span>${docs.length} textos</span></summary><div>${docs.slice(0,7).map(doc=>`<a href="#/reader/${encodeURIComponent(doc.id)}">${esc(doc.title)}</a>`).join("")}</div></details>`).join("")}</div></section><section class="v7-opus-latest">${section("Actualidad","Último de Opus Dei","Dos contenidos recientes, renovados por la actualización diaria.")}<div>${latest.map(item=>`<a href="${esc(item.url)}" target="_blank" rel="noopener" style="--opus-image:url('${esc(item.image||"")}')"><span>${esc(item.date||"Opus Dei")}</span><h3>${esc(item.title)}</h3><p>${esc(item.description||"")}</p><b>Leer ↗</b></a>`).join("")||`<a class="v7-opus-latest-empty" href="https://opusdei.org/es/" target="_blank" rel="noopener"><span>Actualización en curso</span><h3>Consulta Opusdei.org</h3><p>Atlas volverá a intentarlo en la siguiente actualización diaria.</p><b>Abrir ↗</b></a>`}</div></section></section>`;
  }
  function renderLearning(){const studying=location.hash.includes("/estudiar");const faq=(window.ATLAS_FAQ?.items||[]).slice(0,6);const questions=faq.length?faq.map(item=>`<details><summary>${esc(item.question||item.title)}</summary><p>${esc(item.answer||item.text||"")}</p></details>`).join(""):`<details open><summary>¿Por dónde empiezo?</summary><p>Elige una pregunta concreta, abre el especialista sugerido y comprueba las fuentes.</p></details><details><summary>¿Cómo busco una cita?</summary><p>Usa el buscador y activa la búsqueda literal dentro de los documentos.</p></details>`;return `<section class="page atlas-v7 v7-learning learning-polished"><header class="v7-page-hero"><span>Formación acompañada</span><h1>${studying?"Estudiar con método":"Quiero aprender"}</h1><p>${studying?"Mapas, cronologías y conexiones para profundizar.":"Preguntas típicas, recorridos y un punto de partida claro."}</p></header><nav class="v7-learning-switch"><a class="${studying?"":"active"}" href="#/formarse">Aprender</a><a class="${studying?"active":""}" href="#/formarse/estudiar">Estudiar</a></nav>${studying?`<section class="learning-tools">${[["↔","Cronología viva","#/timeline"],["◎","Mapa mundial","#/map"],["⌘","Relaciones","#/graph"],["✦","Capacidades","#/compare"]].map(([icon,title,url])=>`<a href="${url}"><i>${icon}</i><b>${title}</b><span>Abrir herramienta →</span></a>`).join("")}</section>`:`<section class="learning-questions">${section("Preguntas típicas","Empieza por una pregunta real.","Respuestas breves para orientarte y enlaces para profundizar.")}<div>${questions}</div><a class="secondary-button" href="#/faq">Ver todas las preguntas frecuentes →</a></section><section class="learning-tools learning-start">${[["✦","Historia de la Salvación","#/salvation"],["⌕","¿Dónde buscar?","#/preguntar"],["◌","Rutas de estudio","#/routes"],["♧","Colecciones","#/collections"]].map(([icon,title,url])=>`<a href="${url}"><i>${icon}</i><b>${title}</b><span>Empezar →</span></a>`).join("")}</section>`}</section>`}
  const originalLibrary=A.architecture.renderLibrary;
  A.architecture.renderLibrary=route=>{let html=originalLibrary(route);if((route.query.get("view")||"shelves")==="shelves"){const featured=`<section class="library-doctrine-shortcuts"><a href="#/catecismo"><span>✦</span><b>Catecismo</b><small>Fe explicada · consulta rápida</small></a><a href="#/vaticano-ii"><span>Ⅱ</span><b>Concilio Vaticano II</b><small>Documentos fundamentales</small></a></section>`;html=html.replace(/(<section class="v7-shelf-group")/,`${featured}$1`)}return html};
  A.architecture.renderOpusDei=renderOpusDei;A.architecture.renderLearning=renderLearning;
  const filters=document.querySelector("#search-filters"), fulltext=document.querySelector(".fulltext-bar");
  if(filters&&fulltext&&!filters.closest("details")){const advanced=document.createElement("details");advanced.className="search-advanced";advanced.innerHTML="<summary>Limitar la búsqueda <span>IA, tipo o fuente</span></summary>";filters.before(advanced);advanced.append(filters,fulltext);}
  document.addEventListener("click",event=>{const button=event.target.closest(".v7-topic-cloud button[data-search-term]");if(!button)return;event.preventDefault();event.stopImmediatePropagation();const topic=button.dataset.searchTerm,docs=A.data.documents.filter(doc=>doc.category===topic).slice(0,80),cloud=button.closest(".v7-topic-cloud");cloud.classList.add("is-drilled");cloud.innerHTML=`<header><button type="button" data-topic-back>← Todos los temas</button><h2>${esc(topic)}</h2><p>${docs.length} fuentes organizadas para leer directamente.</p></header><div class="topic-document-drill">${docs.map(doc=>`<a href="#/reader/${encodeURIComponent(doc.id)}"><span>${esc(doc.library.short)}</span><b>${esc(doc.title)}</b><small>${esc(doc.author||doc.category)}</small></a>`).join("")}</div>`;},{capture:true});
  document.addEventListener("click",event=>{const button=event.target.closest("[data-topic-back]");if(!button)return;location.hash="#/biblioteca?view=topics"},{capture:true});
})();
