(function () {
  "use strict";
  const A = window.Atlas = window.Atlas || {};
  const esc = value => A.library.esc(String(value || ""));
  const covers = { canon:"canoniaportada.webp",history:"historiaportada.webp",liturgy:"liturgiaportada.webp",ortodoxia:"ortodoxiaportada.webp",cinepilot:"cinepilotportada.webp",bibliotecaria:"bibliotecariaportada.webp",clasicos:"clasicosportada.webp","san-josemaria":"portadaSanJosemarIA.webp","preparadora-circulos":"preparadordecirculosportada.webp","vida-santos":"santosportada.png","meditacion-diaria":"meditaciondiariaportada.png" };
  const libraryLines = {doctrine:"Doctrina, teología y moral católica.",canon:"Normas y fuentes del Derecho Canónico.",history:"Historia de la Iglesia y Padres en contexto.",liturgy:"Comprende y celebra la liturgia.",ortodoxia:"IA orientada a explicar doctrina y moral para el debate público.",cinepilot:"Cine con criterio artístico y moral.",bibliotecaria:"Encuentra tu próxima lectura.",clasicos:"Grandes obras para leer con orden.","san-josemaria":"Obras y vida de san Josemaría.","preparadora-circulos":"Prepara círculos con fuentes fiables.","vida-santos":"Aprende de vidas reales de santos.","meditacion-diaria":"Una IA para ayudarte a rezar"};
  const prayerSituations = [
    "No tengo ganas de rezar y me cuesta incluso empezar. Ayúdame a ponerme con sinceridad delante de Dios sin fingir sentimientos que ahora no tengo.",
    "Acabo de comulgar. Ayúdame a dar gracias despacio, a mirar a Jesús y a pedir una fe mucho mayor y más concreta.",
    "Me siento solo aunque estoy rodeado de gente. Necesito hablar contigo y descubrir que no estoy abandonado.",
    "Me han engañado y no consigo perdonar. Ayúdame a reconocer la herida sin alimentar el rencor y a pedir la gracia de dar un primer paso.",
    "Me arrepiento de una decisión y sigo pensando en ella. Ayúdame a aprender, pedir perdón si hace falta y dejar de vivir atrapado en el pasado.",
    "Siento envidia de la vida de otras personas y termino despreciando la mía. Enséñame a agradecer, a mirar con verdad y a desear el bien ajeno.",
    "No comprendo por qué Dios permite este dolor. No quiero una explicación fácil: ayúdame a permanecer delante de Él y a no perder la confianza.",
    "La Cruz me está superando y tengo miedo de no poder más. Ayúdame a pedir ayuda, a vivir solo el día de hoy y a encontrar a Cristo conmigo.",
    "No estoy cuidando bien mi corazón ni lo que miro, pienso y deseo. Ayúdame a ser sincero y a recomenzar con decisiones concretas.",
    "Tengo miedo del futuro y trato de controlarlo todo. Ayúdame a distinguir lo que debo hacer hoy de lo que necesito confiar a Dios.",
    "Estoy dudando de si merece la pena seguirte. Ayúdame a hablarte con franqueza, recordar lo vivido y escuchar sin forzar una respuesta.",
    "Necesito pedir perdón, pero me justifico y temo quedar mal. Ayúdame a llamar a las cosas por su nombre y a reparar el daño.",
    "Quiero dar gracias y no sé cómo. Recorre conmigo el día y ayúdame a reconocer dones concretos, personas y pequeñas misericordias.",
    "Estoy enfadado con Dios. Ayúdame a no esconderlo, a rezar desde esta verdad y a permanecer en la conversación aunque no entienda."
    ,"Estoy agradecido por una persona concreta. Enséñame a dar gracias sin prisa y a quererla mejor hoy."
    ,"Tengo que tomar una decisión importante. Dame libertad interior, consejo oportuno y valentía para elegir el bien."
    ,"Me cuesta estudiar o trabajar con orden. Ayúdame a empezar, a terminar lo que debo y a ofrecértelo."
    ,"He cometido el mismo error otra vez. Dame humildad para confesarlo, paciencia para recomenzar y esperanza."
    ,"Estoy preocupado por alguien que sufre. Pon su nombre en mi oración y enséñame qué ayuda concreta puedo darle."
    ,"No sé qué hacer con mi vocación y mi futuro. Ayúdame a escuchar, a no adelantarme y a ser generoso."
    ,"Voy a ver a mi familia y hay tensión. Dame palabras limpias, capacidad de escuchar y deseo de servir."
    ,"Me he distraído mucho y he desperdiciado el día. Ayúdame a cerrar la jornada con verdad y sin desesperarme."
    ,"Siento vergüenza de acercarme a Ti. Recuérdame que tu misericordia llega antes que mi miedo."
    ,"Quiero rezar por la Iglesia y por el Papa. Enséñame a hacerlo con fe, unidad y sentido sobrenatural."
    ,"Estoy viviendo una alegría grande. Ayúdame a reconocer que viene de Ti y a compartirla sin presumir."
    ,"No encuentro silencio dentro de mí. Quédate conmigo en medio del ruido y enséñame a escuchar."
  ];
  const groups = [
    { id:"fe", title:"Fe e Iglesia", subtitle:"Escritura, doctrina, normas y celebración", libraries:["doctrine","canon","liturgy","ortodoxia"] },
    { id:"tradicion", title:"Historia y tradición", subtitle:"Padres, Iglesia y vidas que atravesaron los siglos", libraries:["history","vida-santos"] },
    { id:"espiritualidad", title:"Espiritualidad", subtitle:"Oración, vida ordinaria y acompañamiento", libraries:["san-josemaria","meditacion-diaria"] },
    { id:"cultura", title:"Cultura", subtitle:"Literatura, clásicos y cine", libraries:["clasicos","bibliotecaria","cinepilot"] }
  ];
  const routeCards = [
    ["Comprender la Misa","6 pasos","liturgy","#/spiritual/mass","Una celebración que se aprende desde dentro."],
    ["Historia de la Salvación","Mapa completo","salvation","#/salvation","De Abraham a Jesucristo, de la promesa a la alianza nueva."],
    ["Conocer a los Padres","Fuentes y épocas","history","#/library/history/documents","Autores, concilios y textos en contexto."],
    ["Derecho Canónico","Introducción","canon","#/library/canon/documents","Normas, fuentes y distinciones fundamentales."],
    ["Matrimonio y familia","Ruta transversal","doctrine","#/guide?q=matrimonio","Doctrina, derecho, liturgia e historia."],
    ["Grandes clásicos","Plan de lectura","clasicos","#/library/clasicos/documents","Obras y autores para leer con orden."],
    ["Historia de la Iglesia","Cronología viva","history","#/timeline","Acontecimientos, autores y documentos fechados."]
  ];
  const generalExamQuestions = [
    ["Agradecer","¿Qué bien concreto he recibido hoy? ¿He reconocido a las personas que me han ayudado?"],
    ["Delante de Dios","¿He buscado a Dios, aunque fuera brevemente, o he vivido todo el día como si estuviera solo?"],
    ["Amar","¿A quién he tratado con paciencia? ¿A quién he ignorado, utilizado o juzgado sin conocer su lucha?"],
    ["Deberes","¿He cumplido con honradez mi trabajo, estudio y responsabilidades, o he dejado que otros cargaran con lo mío?"],
    ["Verdad","¿He mentido, exagerado, ocultado algo importante o cuidado demasiado mi imagen?"],
    ["Corazón","¿Qué he dejado entrar por mis ojos, pensamientos y deseos? ¿Me ha hecho más libre y capaz de amar?"],
    ["Perdón","¿Guardo rencor? ¿Necesito pedir perdón, reparar un daño o dar un primer paso?"],
    ["Quien sufre","¿He visto las necesidades cercanas? ¿He acompañado, escuchado o ayudado de manera concreta?"],
    ["Recomenzar","¿Qué quiero entregar a la misericordia de Dios y qué pequeño propósito realista puedo vivir mañana?"]
  ];

  function daySeed() { const now=new Date(),start=new Date(now.getFullYear(),0,0);return Math.floor((now-start)/86400000); }
  function pick(items,offset=0) { return items?.length ? items[(daySeed()+offset)%items.length] : null; }
  function cleanText(value) { return String(value||"").replace(/\*{1,3}/g,"").replace(/\s+/g," ").trim(); }
  function cover(lib) { return covers[lib?.id] ? `../assets/images/libraries/${covers[lib.id]}` : "../assets/images/atlas-library-fallback.svg"; }
  function availableLibraries() { return A.data.catalog.libraries.filter(lib=>!lib.unlockFeature||A.storage.isFeatureUnlocked(lib.unlockFeature)); }
  function sectionHeader(kicker,title,text,action="") { return `<header class="v7-section-head"><div><span>${esc(kicker)}</span><h2>${esc(title)}</h2>${text?`<p>${esc(text)}</p>`:""}</div>${action}</header>`; }
  function searchButton(label="Buscar libros, autores, temas, santos, documentos…") { return `<button class="v7-global-search" data-action="search">${A.library.icon("search")}<span>${esc(label)}</span><kbd>Ctrl K</kbd></button>`; }
  function libraryTile(lib) { return `<a class="v7-library-tile tone-${lib.tone}" data-library="${esc(lib.id)}" href="#/library/${encodeURIComponent(lib.id)}/documents" style="--v7-cover:url('${cover(lib)}')"><span>${esc(lib.mark)}</span><div><small>${lib.stats.documents} fuentes</small><h3>${esc(lib.short)}</h3><p>${esc(libraryLines[lib.id]||lib.description||"Explorar biblioteca")}</p></div></a>`; }
  function specialistTile(lib) { const direct=lib.notebookUrl||`#/library/${encodeURIComponent(lib.id)}/documents`;return `<a class="v7-library-tile v7-specialist-direct tone-${lib.tone}" data-library="${esc(lib.id)}" href="${esc(direct)}" ${lib.notebookUrl?'target="_blank" rel="noopener"':""} style="--v7-cover:url('${cover(lib)}')"><span>${esc(lib.mark)}</span><div><small>${lib.stats.documents} fuentes</small><h3>${esc(lib.short)}</h3><p>${esc(libraryLines[lib.id]||lib.description||"Consultar especialista")}</p><b>${lib.notebookUrl?"Abrir IA directamente ↗":"Abrir biblioteca →"}</b></div></a>`; }
  function continueData() {
    const stored=A.storage.get();
    const reading=Object.entries(stored.readerProgress||{}).map(([id,progress])=>({doc:A.data.documentMap.get(id),progress})).filter(item=>item.doc).sort((a,b)=>Date.parse(b.progress.updatedAt||0)-Date.parse(a.progress.updatedAt||0)).slice(0,1);
    const route=Object.entries(stored.routeProgress||{}).map(([id,docs])=>({route:(A.data.catalog.routes||[]).find(item=>item.id===id),count:docs.length})).filter(item=>item.route).slice(0,1);
    const recent=(stored.history||[]).map(id=>A.data.documentMap.get(id)).filter(Boolean).slice(0,1);
    return {reading,route,recent};
  }

  function renderHome() {
    const madridToday=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Madrid"}).format(new Date());
    const liveGospel=(window.ATLAS_EXTERNAL?.items||[]).find(item=>item.type==="gospel"&&item.date===madridToday);
    const gospel=liveGospel||pick(window.ATLAS_GOSPEL_MEDITATIONS?.meditations||[],0);
    const gospelUrl=`https://opusdei.org/es/gospel/${madridToday}/`;
    const saint=pick(A.data.documents.filter(doc=>doc.libraryId==="vida-santos"),7);
    const meditation=window.ATLAS_TEN_MINUTES?.episodes?.[0] || pick(window.ATLAS_GOSPEL_MEDITATIONS?.meditations||[],4);
    const discovery=pick([...(window.ATLAS_EXTERNAL?.items||[]),...(A.data.catalog.shorts||[])],11);
    const ongoing=continueData();
    return `<section class="page atlas-v7 v7-home">
      <header class="v7-home-hero"><span>Atlas · Mercabá</span><h1>Todo reunido.<br><em>Todo aquí.</em></h1><p>Una biblioteca católica viva para leer, comprender, rezar y descubrir. <strong>Con ayuda de las IA para preguntar, encontrar respuestas en las fuentes y rezar.</strong></p>${searchButton()}<div class="v7-home-share"><button class="primary-button" data-action="share-public-app">Compartir Atlas ↗</button><button class="secondary-button" data-action="open-qr">Ver QR</button></div><a class="v7-discover-atlas-link" href="#/descubre-atlas">Descubre todo lo que contiene Atlas →</a></header>
      <section class="v7-home-three">${sectionHeader("Atlas en tres gestos","Una biblioteca. IA sobre sus fuentes. Recursos para vivir.","Todo empieza en los textos y termina en una ayuda concreta para tu día.")}<div><a href="#/biblioteca" class="home-three-library"><i>01</i><b>Biblioteca</b><span>Doctrina, Biblia, santos, literatura y documentos que puedes leer.</span></a><a href="#/preguntar" class="home-three-ai"><i>02</i><b>IA sobre la biblioteca</b><span>Especialistas para preguntar usando las fuentes de cada cuaderno.</span></a><a href="#/rezar" class="home-three-life"><i>03</i><b>Rezar, formarse y leer</b><span>Evangelio, examen, rutas, Misa y propuestas para vivir hoy.</span></a></div></section>
      <section class="v7-today">${sectionHeader("Hoy","Una pausa en lo importante","Tres puertas para este día.")}<div class="v7-today-grid">
        <a href="${esc(gospelUrl)}" target="_blank" rel="noopener" class="v7-today-card gospel"><i>☼</i><small>Evangelio y oración · hoy</small><h3>${esc(gospel?.title||"Rezar el Evangelio de hoy")}</h3><p>${esc(gospel?.description||"Entra en la escena y mira especialmente a Cristo.")}</p></a>
        <a href="${saint?`#/reader/${encodeURIComponent(saint.id)}`:"#/spiritual/saints"}" class="v7-today-card saint"><i>✦</i><small>Un santo para hoy</small><h3>${esc(saint?.title||"Una vida que acompaña")}</h3><p>Lee una escena real y descubre cómo vivió la fe.</p></a>
        <article class="v7-today-card meditation v7-daily-listen"><i class="ten-minutes-logo" aria-label="10 Minutos con Jesús">10′</i><small>10 Minutos con Jesús · hoy</small><h3>${esc(meditation?.title||"Un rato de oración")}</h3><p>${esc(cleanText(meditation?.description||"Escucha, lee y vuelve a lo esencial."))}</p>${meditation?.audioUrl?`<audio controls preload="metadata" src="${esc(meditation.audioUrl)}"></audio>`:""}<a href="${esc(meditation?.pageUrl||meditation?.url||"#/rezar")}" ${meditation?.pageUrl||meditation?.url?`target="_blank" rel="noopener"`:""}>Abrir episodio ↗</a></article>
      </div></section>
      ${(ongoing.reading.length||ongoing.route.length||ongoing.recent.length)?`<section class="v7-continue">${sectionHeader("Continúa","Retoma donde estabas","Solo lo más relevante.",`<a href="#/mi-atlas">Ver Mi Atlas</a>`)}<div>${ongoing.reading.map(({doc,progress})=>`<a href="#/reader/${encodeURIComponent(doc.id)}"><span>Lectura</span><b>${esc(doc.title)}</b><i>${Math.round((progress.scrollRatio||0)*100)}%</i></a>`).join("")}${ongoing.route.map(item=>`<a href="#/route/${item.route.id}"><span>Ruta</span><b>${esc(item.route.title)}</b><i>${item.count} pasos</i></a>`).join("")}${ongoing.recent.map(doc=>`<a href="#/document/${encodeURIComponent(doc.id)}"><span>Reciente</span><b>${esc(doc.title)}</b><i>→</i></a>`).join("")}</div></section>`:""}
      <section class="v7-intents">${sectionHeader("Empieza aquí","¿Qué quieres hacer?","Cuatro acciones; toda la profundidad detrás.")}<div><a href="#/biblioteca"><i>Le</i><b>Leer</b><span>Libros, Biblia y documentos</span></a><a href="#/preguntar"><i>?</i><b>Preguntar</b><span>Encuentra al especialista adecuado</span></a><a href="#/rezar"><i>✦</i><b>Rezar</b><span>Evangelio, santos y meditación</span></a><a href="#/formarse"><i>↗</i><b>Aprender</b><span>Rutas y conocimiento ordenado</span></a></div></section>
      <section class="v7-discovery">${sectionHeader("Descubre","Una recomendación de Atlas","Una sola pieza para abrir una puerta.",`<a href="#/discover">Ver más</a>`)}<a href="${esc(discovery?.url||`#/short/${discovery?.id||""}`)}" ${discovery?.url?`target="_blank" rel="noopener"`:""} style="--v7-image:url('${esc(discovery?.image||"../assets/images/libraries/historiaportada.webp")}')"><span>${esc(discovery?.source||discovery?.type||"Atlas")}</span><h2>${esc(discovery?.title||"Explora una historia, una idea o una fuente")}</h2><p>${esc(discovery?.description||discovery?.text||"Cada descubrimiento conduce a contenidos y fuentes de Atlas.")}</p></a></section>
    </section>`;
  }

  function renderLibrary(route) {
    const view=route.query.get("view")||"shelves", libs=availableLibraries();
    const tabs=[["shelves","Estanterías"],["topics","Temas"],["authors","Autores"],["collections","Colecciones"]];
    let content="";
    if(view==="shelves") {
      const groupedIds=new Set(groups.flatMap(group=>group.libraries));
      const dynamic=libs.filter(lib=>!groupedIds.has(lib.id));
      content=`<div class="v7-shelves"><section class="v7-bible-shelf"><div><span>Sagradas Escrituras</span><h2>La Biblia, en dos ediciones.</h2><p>CEE como texto principal y Jerusalén como edición de estudio.</p></div><a href="#/bible"><b>Biblia CEE</b><small>Edición oficial · principal</small></a><a href="#/bible/jerusalem"><b>Biblia de Jerusalén</b><small>Estudio y comparación</small></a></section>${groups.map(group=>{const items=group.libraries.map(id=>libs.find(lib=>lib.id===id)).filter(Boolean);return items.length?`<section class="v7-shelf-group">${sectionHeader(group.title,group.title,group.subtitle)}<div>${items.map(libraryTile).join("")}</div></section>`:"";}).join("")}${dynamic.length?`<section class="v7-shelf-group">${sectionHeader("Tus bibliotecas","Más bibliotecas","IA desbloqueadas o detectadas automáticamente.")}<div>${dynamic.map(libraryTile).join("")}</div></section>`:""}</div>`;
    }
    if(view==="topics"){const counts=new Map();A.data.documents.forEach(doc=>counts.set(doc.category,(counts.get(doc.category)||0)+1));content=`<div class="v7-topic-cloud">${[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,48).map(([name,count])=>`<button data-action="search" data-search-term="${esc(name)}"><b>${esc(name)}</b><span>${count} fuentes</span></button>`).join("")}</div>`;}
    if(view==="authors"){const counts=new Map();A.data.documents.forEach(doc=>{if(doc.author)counts.set(doc.author,(counts.get(doc.author)||0)+1)});content=`<div class="v7-author-list">${[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,60).map(([name,count])=>`<a href="#/author/${encodeURIComponent(name)}"><span>${esc(name.split(/\s+/).map(x=>x[0]).slice(0,2).join(""))}</span><b>${esc(name)}</b><small>${count} textos</small></a>`).join("")}</div>`;}
    if(view==="collections") content=`<div class="v7-collection-list">${(A.data.catalog.collections||[]).map(item=>`<a href="#/collection/${item.id}"><span>${item.documentIds?.length||item.documents?.length||0}</span><h3>${esc(item.title)}</h3><p>${esc(item.description||"Colección temática de Atlas")}</p></a>`).join("")}</div>`;
    return `<section class="page atlas-v7 v7-library"><header class="v7-page-hero"><span>El corazón de Atlas</span><h1>Biblioteca</h1><p>Busca, explora, lee, guarda, estudia y comparte.</p>${searchButton()}</header><nav class="v7-view-tabs">${tabs.map(([id,label])=>`<a class="${view===id?"active":""}" href="#/biblioteca?view=${id}">${label}</a>`).join("")}</nav>${content}</section>`;
  }

  function recommend(query) {
    const normalized=A.data.normalize(query), tokens=normalized.split(/\s+/).filter(x=>x.length>2);
    const intents={canon:["canon","nulidad","validez","licitud","impedimento","tribunal","derecho"],liturgy:["misa","liturgia","rito","misal","sacramento","altar"],history:["historia","padres","concilio","nicea","agustin","siglo"],cinepilot:["pelicula","cine","actor","director","edad"],bibliotecaria:["novela","literatura","poesia","leer","autor"],clasicos:["clasico","shakespeare","dostoievski","homero"],"san-josemaria":["josemaria","camino","surco","forja","trabajo"],"vida-santos":["santo","santos","biografia","vocacion"],"meditacion-diaria":["rezar","oracion","miedo","dolor","perdon","soledad"],doctrine:["iglesia","doctrina","moral","conciencia","catecismo","fe","pecado"]};
    const scores=new Map();Object.entries(intents).forEach(([id,words])=>scores.set(id,words.reduce((n,w)=>n+(normalized.includes(w)?6:0),0)));A.data.documents.forEach(doc=>{const hay=A.data.normalize(`${doc.title} ${doc.category} ${doc.author||""}`),score=tokens.reduce((n,t)=>n+(hay.includes(t)?1:0),0);if(score)scores.set(doc.libraryId,(scores.get(doc.libraryId)||0)+score)});
    const ranked=[...scores.entries()].sort((a,b)=>b[1]-a[1]).map(([id,score])=>({lib:A.data.libraryMap.get(id),score})).filter(item=>item.lib&&(!item.lib.unlockFeature||A.storage.isFeatureUnlocked(item.lib.unlockFeature)));
    const docs=A.data.documents.map(doc=>({doc,score:tokens.reduce((n,t)=>n+(A.data.normalize(`${doc.title} ${doc.category} ${doc.author||""}`).includes(t)?1:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,6).map(x=>x.doc);
    return {primary:ranked[0]||{lib:A.data.libraryMap.get("doctrine"),score:0},others:ranked.slice(1,4),docs};
  }
  function renderAsk(route) {
    const query=(route.query.get("q")||"").trim(), examples=["¿Qué enseña la Iglesia sobre la conciencia?","¿Qué requisitos existen para ser padrino?","¿Cómo vivían la Eucaristía los primeros cristianos?","¿Qué novela leer después de Dostoievski?"];
    let answer="";if(query){const result=recommend(query),lib=result.primary.lib,prompt=`${query}\n\nResponde apoyándote en las fuentes del cuaderno. Distingue hechos, normas u opiniones cuando proceda y cita los documentos utilizados.`;answer=`<section class="v7-ask-result"><span>Mejor punto de partida</span><div class="v7-specialist" style="--v7-cover:url('${cover(lib)}')"><small>La mejor opción es</small><h2>${esc(lib.short)}</h2><p>${esc(lib.description||lib.purpose)}</p></div><div class="v7-prepared-query"><small>Consulta preparada</small><blockquote>${esc(prompt)}</blockquote><button class="primary-button" data-architecture-notebook="${esc(lib.notebookUrl||"")}" data-architecture-prompt="${esc(prompt)}">Copiar y abrir en NotebookLM ↗</button></div>${result.others.length?`<div class="v7-other-specialists"><span>Especialistas complementarios</span>${result.others.map(item=>`<a href="#/library/${item.lib.id}/documents"><b>${esc(item.lib.short)}</b><small>Ver por qué puede ayudar →</small></a>`).join("")}</div>`:""}${result.docs.length?`<div class="v7-useful-sources">${sectionHeader("En Atlas","Otras fuentes útiles","Para leer y comprobar antes o después de preguntar.")}${result.docs.map(doc=>`<a href="#/reader/${encodeURIComponent(doc.id)}"><span>${esc(doc.library.short)}</span><b>${esc(doc.title)}</b><small>${esc(doc.author||doc.category)}</small></a>`).join("")}</div>`:""}</section>`;}
    return `<section class="page atlas-v7 v7-ask"><header><span>Pregunta a especialistas</span><h1>¿Qué quieres comprender?</h1><p>Atlas no responde doctrinalmente: encuentra el cuaderno adecuado y prepara una consulta útil.</p><form id="v7-ask-form"><textarea name="q" rows="4" placeholder="Escribe tu pregunta…">${esc(query)}</textarea><button>Encontrar especialista</button></form><div class="v7-question-examples">${examples.map(item=>`<a href="#/preguntar?q=${encodeURIComponent(item)}">${esc(item)}</a>`).join("")}</div></header>${answer}<section class="v7-specialists-open" id="v7-specialists"><span>Especialistas disponibles</span><h2>Abre directamente la IA que necesitas.</h2><p>Cada tarjeta conduce a su cuaderno de NotebookLM, no a la ficha de biblioteca.</p><div class="v7-specialists-grid">${availableLibraries().map(specialistTile).join("")}</div></section></section>`;
  }

  function renderPrayer(route) {
    const start=daySeed()%prayerSituations.length,examples=[0,1,2].map(i=>prayerSituations[(start+i)%prayerSituations.length]),query=route.query.get("q")||"";
    const meditation=A.data.libraryMap.get("meditacion-diaria"),daily=window.ATLAS_TEN_MINUTES?.episodes?.[0];
    const openers=["Jesús, no sé muy bien qué decirte, pero quiero quedarme aquí contigo.","Señor, gracias por lo bueno de hoy, también por lo que casi no he visto.","Ayúdame a confiarte esto que me preocupa y a vivir el siguiente paso.","Perdóname. Dame luz para reparar y fuerza para volver a empezar."];
    const openerStart=Math.floor(Math.random()*openers.length),visibleOpeners=[0,1].map(index=>openers[(openerStart+index)%openers.length]);
    return `<section class="page atlas-v7 v7-prayer"><header class="v7-prayer-hero"><span>Un lugar sereno dentro de Atlas</span><h1>No sé rezar.</h1><p class="v7-prayer-lede">Empieza como puedas. Él ya está escuchando.</p><form id="v7-prayer-form" class="v7-prayer-composer"><label><span class="sr-only">Lo que quieres decir a Dios</span><textarea name="q" rows="2" placeholder="Jesús, hoy…">${esc(query)}</textarea></label><button><span>Preparar oración</span> →</button></form><div class="v7-prayer-openers"><span>O empieza con una frase</span>${visibleOpeners.map(item=>`<button type="button" data-prayer-example="${esc(item)}">«${esc(item)}»</button>`).join("")}</div>${query?`<div class="v7-prayer-ready"><small>Esto es lo que llevarás a Palabras para orar</small><blockquote>${esc(query)}</blockquote><button data-architecture-notebook="${esc(meditation?.notebookUrl||"")}" data-architecture-prompt="${esc(`Ayúdame a hacer oración desde esta situación concreta: ${query}`)}">Copiar y abrir Palabras para orar ↗</button></div>`:""}<details class="v7-prayer-more"><summary>Más situaciones</summary><div>${examples.map(item=>`<a href="#/rezar?q=${encodeURIComponent(item)}">${esc(item)}</a>`).join("")}${prayerSituations.slice(3).map(item=>`<a href="#/rezar?q=${encodeURIComponent(item)}">${esc(item)}</a>`).join("")}</div></details></header>
      <section class="v7-prayer-now"><article><span><i class="ten-minutes-logo" aria-hidden="true">10′</i> 10 Minutos con Jesús · hoy</span><h2>${esc(daily?.title||"Una meditación para hoy")}</h2><p>${esc(cleanText(daily?.description||"Diez minutos para escuchar y hacer oración."))}</p>${daily?.audioUrl?`<audio controls preload="metadata" src="${esc(daily.audioUrl)}"></audio>`:""}${daily?.pageUrl?`<a href="${esc(daily.pageUrl)}" target="_blank" rel="noopener">Abrir episodio ↗</a>`:""}</article><a href="https://misas.org/" target="_blank" rel="noopener"><i>✚</i><span>Misa cerca de ti</span><h2>Horarios de Misa</h2><p>Consulta iglesias y celebraciones por lugar y hora.</p><b>Abrir misas.org ↗</b></a></section>
      <section class="v7-prayer-grid"><a class="featured" href="#/spiritual/gospel"><i>☼</i><span>Evangelio y meditaciones</span><h2>Rezar el Evangelio</h2><p>Entra en la escena, mira a Cristo y convierte la lectura en conversación.</p></a><a href="#/spiritual/saints"><i>✦</i><h3>Santos</h3><p>Experiencias, biografías y cronologías.</p></a><a href="#/music"><i>♪</i><h3>Escuchar</h3><p>10 Minutos con Jesús, música y audios.</p></a><a href="#/examen"><i>◒</i><h3>Examen y confesión</h3><p>Mirar el día con verdad y prepararse.</p></a><a href="#/spiritual/mass"><i>✚</i><h3>Misa</h3><p>Guía de la celebración y sus momentos.</p></a><a class="prayer-songbook-link" href="#/spiritual/songbook"><i>♫</i><h3>Cancionero</h3><p>Cantos para la Misa, adoración y oración.</p></a><article class="devocionario-card"><a href="https://opusdei.org/es/prayers/?pb1=es&pb2=latin" target="_blank" rel="noopener"><i>✧</i><h3>Devocionario</h3><p>Oraciones en español y latín.</p></a><button class="devocionario-save" data-save-question="devocionario">☆ Guardar acceso</button></article><a href="#/spiritual/confession"><i>↺</i><h3>Guía de confesión</h3><p>Preparación, estructura y dudas frecuentes.</p></a></section></section>`;
  }

  function renderLearning() { return `<section class="page atlas-v7 v7-learning"><header class="v7-page-hero"><span>Conocimiento estructurado</span><h1>Quiero aprender</h1><p>Convierte la biblioteca en un camino: empieza sencillo y profundiza cuando lo necesites.</p></header><nav class="v7-learning-switch"><a class="active" href="#/formarse">Aprender</a><a href="#/formarse/estudiar">Estudiar</a></nav>${location.hash.includes("/estudiar")?`<section class="v7-advanced"><header><span>Zona avanzada</span><h2>Estudio avanzado</h2><p>Visualizaciones y herramientas académicas aparecen aquí, no en el primer contacto.</p></header><div><a href="#/timeline"><i>↔</i><b>Cronología viva</b><span>Autores, concilios y documentos.</span></a><a href="#/map"><i>◎</i><b>Mapa mundial</b><span>Lugares, personas y acontecimientos.</span></a><a href="#/graph"><i>⌘</i><b>Relaciones</b><span>Documentos y categorías conectados.</span></a><a href="#/compare"><i>≍</i><b>Capacidades</b><span>Compara especialistas y corpus.</span></a><a href="#/spiritual/timeline"><i>✦</i><b>Cronologías de santos</b><span>Vidas y contemporáneos.</span></a><a href="#/explore"><i>＋</i><b>Más herramientas</b><span>Estadísticas, fuentes y análisis.</span></a></div></section>`:`<section class="v7-learning-routes">${routeCards.map(([title,meta,tone,url,text],index)=>`<a class="tone-${tone}" href="${url}"><span>${String(index+1).padStart(2,"0")} · ${esc(meta)}</span><h2>${esc(title)}</h2><p>${esc(text)}</p><b>Comenzar →</b></a>`).join("")}</section><section class="v7-learning-more">${sectionHeader("Sigue explorando","Más formas de aprender","Rutas, colecciones y planes de lectura.")}<div><a href="#/routes">Rutas verificables</a><a href="#/collections">Colecciones temáticas</a><a href="#/biblioteca?view=authors">Autores</a><a href="#/formarse/estudiar">Estudio avanzado</a></div></section>`}</section>`; }

  function renderOpusDei() {
    const unlocked=A.storage.isFeatureUnlocked("preparadora-circulos");
    const prep=A.data.libraryMap.get("preparadora-circulos"),prepDocs=unlocked?(prep?.documents||[]):[];
    const latest=(window.ATLAS_EXTERNAL?.items||[]).filter(item=>item.source==="Opus Dei").slice(0,2);
    const latestSection=`<section class="v7-opus-latest">${sectionHeader("Actualidad", "Último de Opus Dei", "Tres contenidos recientes, renovados con la actualización diaria.",`<a href="https://opusdei.org/es/" target="_blank" rel="noopener">Ver todo ↗</a>`)}<div>${latest.map(item=>`<a href="${esc(item.url)}" target="_blank" rel="noopener" style="--opus-image:url('${esc(item.image||"")}')"><span>${esc(item.date||"Opus Dei")}</span><h3>${esc(item.title)}</h3><p>${esc(cleanText(item.description))}</p><b>Leer ↗</b></a>`).join("")||`<a class="v7-opus-latest-empty" href="https://opusdei.org/es/" target="_blank" rel="noopener"><span>Opus Dei</span><h3>La actualidad se está actualizando.</h3><p>Abre la fuente oficial mientras Atlas recibe los últimos contenidos.</p><b>Abrir ↗</b></a>`}</div></section>`;
    const resources=`${latestSection}${unlocked?`<section class="v7-opus-resources">${sectionHeader("Corpus disponible",`${prepDocs.length} recursos para formación y círculos`,"Obras de san Josemaría, textos pontificios, Romana y materiales de los prelados.")}<div>${prepDocs.map(doc=>`<a href="#/reader/${encodeURIComponent(doc.id)}"><small>${esc(doc.category)}</small><b>${esc(doc.title)}</b><span>${A.library.compact(doc.words)} palabras →</span></a>`).join("")}</div></section>`:""}`;
    return `<section class="page atlas-v7 v7-opus"><header><span>Recursos reunidos</span><h1>Opus Dei</h1><p>Textos, formación, oración, vídeos y recursos reunidos en un solo lugar.</p></header><section class="v7-opus-lead"><div style="--v7-image:url('../assets/images/fondo_sjm.png')"><span>San Josemaría</span><h2>Encontrar a Dios en la vida ordinaria.</h2><p>Obras, homilías, biografía, frases y vídeos.</p><div><a href="#/library/san-josemaria/documents">Abrir biblioteca</a><a href="#/spiritual/escriva">Escriva.org</a></div></div><a href="#/preguntar?q=${encodeURIComponent("¿Qué enseña san Josemaría sobre la santificación del trabajo?")}"><small>Especialista</small><b>Preguntar a San JosemarIA →</b></a></section><section class="v7-opus-grid"><a href="#/spiritual/gospel"><span>Vida cristiana</span><h3>Rezar</h3><p>Meditaciones, Evangelio y escenas para contemplar.</p></a><a href="#/youth"><span>Jóvenes</span><h3>Youth</h3><p>Historias, vídeos y preguntas para vivir la fe hoy.</p></a><a href="https://www.youtube.com/@opusdei/videos" target="_blank" rel="noopener"><span>Mirar y escuchar</span><h3>Vídeos</h3><p>Vídeos del canal oficial del Opus Dei.</p></a><a href="https://romana.org/" target="_blank" rel="noopener"><span>Estudio</span><h3>Romana</h3><p>Artículos, estudios e información histórica.</p></a><a href="https://opusdei.org/es/section/del-prelado/" target="_blank" rel="noopener"><span>Textos</span><h3>Cartas y documentos</h3><p>Prelado, documentos y materiales públicos.</p></a><a href="https://opusdei.org/es/" target="_blank" rel="noopener"><span>Actualidad</span><h3>Opusdei.org</h3><p>Noticias y recursos oficiales.</p></a></section>${resources}<section class="v7-internal ${unlocked?"unlocked":"locked"}"><span>${unlocked?"Recursos internos activos":"Recursos internos"}</span><h2>${unlocked?"Preparador de Círculos y examen específico":"Contenido protegido en este dispositivo"}</h2><p>${unlocked?"El código OD permanece guardado localmente. Los 38 Markdown están disponibles aquí y el Preparador se abre directamente en NotebookLM.":"Desbloquea localmente el Preparador de Círculos y los recursos específicos para miembros."}</p>${unlocked?`<div><a class="primary-button" href="${esc(prep?.notebookUrl||"")}" target="_blank" rel="noopener">Abrir Preparador de Círculos ↗</a><a class="secondary-button" href="#/examen">Abrir examen completo</a><button class="text-button" data-lock-feature="preparadora-circulos">Volver a bloquear</button></div>`:`<form id="feature-unlock-form"><input name="code" autocomplete="off" placeholder="Código" required><button>Desbloquear</button></form>`}</section></section>`;
  }

  function renderMyAtlas() {
    const stored=A.storage.get(), annotations=Object.values(stored.annotations||{}).flat().length, reading=Object.keys(stored.readerProgress||{}).length, unlocked=A.storage.isFeatureUnlocked("preparadora-circulos");
    return `<section class="page atlas-v7 v7-my"><header><span class="v7-avatar">A</span><div><small>Tu espacio personal · Atlas ${esc(A.data.catalog.meta.dataVersion)}</small><h1>Mi Atlas</h1><p>Todo permanece en este dispositivo salvo que decidas exportarlo.</p></div><button data-action="settings">Personalizar</button></header><section class="v7-my-stats"><a href="#/saved"><b>${stored.favorites.documents.length}</b><span>Libros y documentos</span></a><a href="#/saved"><b>${annotations}</b><span>Notas y subrayados</span></a><a href="#/saved"><b>${reading}</b><span>Lecturas iniciadas</span></a></section><section class="v7-my-menu"><a href="#/saved"><b>Guardados</b><span>Libros, Shorts, colecciones y preguntas.</span></a><a href="#/saved"><b>Continuar leyendo</b><span>Progreso e historial reciente.</span></a><a href="#/notifications"><b>Notificaciones</b><span>Decide qué avisos quieres recibir.</span></a><button data-action="settings"><b>Personalización</b><span>Colores, tipografías, movimiento y navegación.</span></button><a href="#/updates"><b>Versión ${esc(A.data.catalog.meta.dataVersion)}</b><span>Comprueba qué ha cambiado y actualiza Atlas.</span></a><a href="#/saved"><b>Importar, exportar y almacenamiento</b><span>Copia local de tus datos y gestión del dispositivo.</span></a></section><section class="v7-my-privacy"><span>Privacidad y recursos internos</span><h2>${unlocked?"OD desbloqueado en este dispositivo":"Recursos OD bloqueados"}</h2><p>Notas, examen, historial y desbloqueos se almacenan localmente.</p>${unlocked?`<button data-lock-feature="preparadora-circulos">Volver a bloquear recursos OD</button>`:`<form id="feature-unlock-form"><input name="code" placeholder="Código" autocomplete="off" required><button>Desbloquear</button></form>`}</section></section>`;
  }
  function renderMore() { return `<section class="page atlas-v7 v7-more"><header><span>Todo Atlas</span><h1>Más</h1><p>Cada puerta tiene su propio carácter. Entra por la que necesites hoy.</p></header><div class="v7-more-grid"><a class="v7-more-card more-formarse" href="#/formarse"><small>Conocimiento ordenado</small><i>↗</i><b>Formarse</b><span>Rutas, Historia y estudio avanzado.</span></a><a class="v7-more-card more-descubrir" href="#/discover"><small>Un feed vivo</small><i>✦</i><b>Descubrir</b><span>Vídeos, música, frases y lecturas.</span></a><a class="v7-more-card more-opus" href="#/opus-dei"><small>Todo reunido</small><i>OD</i><b>Opus Dei</b><span>Textos, oración, Youth y recursos.</span></a><a class="v7-more-card more-atlas" href="#/mi-atlas"><small>Tu espacio</small><i>A</i><b>Mi Atlas</b><span>Guardados, progreso y ajustes.</span></a><a class="v7-more-card more-presentacion" href="#/descubre-atlas"><small>En pocos gestos</small><i>▶</i><b>Descubre Atlas</b><span>Una presentación visual para conocer y compartir la app.</span></a></div></section>`; }

  function renderDiscoverAtlas() {
    const scenes = [
      ["01","Una gran biblioteca","Biblia, santos, doctrina, Padres, clásicos y miles de documentos.","biblioteca","#/biblioteca"],
      ["02","Pregunta a especialistas","Atlas comprende la duda, recomienda la IA y prepara la consulta.","preguntar","#/preguntar"],
      ["03","Aprende con un mapa","Rutas, Historia de la Salvación, cronologías y relaciones.","aprender","#/formarse"],
      ["04","Reza desde tu vida","Evangelio, Palabras para orar, santos, examen y Misa.","rezar","#/rezar"],
      ["05","Descubre cada día","Vídeos, música, noticias, lecturas, citas y preguntas.","descubrir","#/discover"],
      ["06","Opus Dei, reunido","San Josemaría, Youth, Escriva.org, Romana y recursos.","opus","#/opus-dei"]
    ];
    return `<section class="page atlas-v7 v7-atlas-story"><header><span>Todo reunido · Todo aquí</span><h1>Descubre Atlas</h1><p>Seis gestos. Una sola aplicación. Desliza para ver todo lo que normalmente está disperso.</p></header><div class="v7-story-track">${scenes.map(([number,title,text,tone,url])=>`<a class="story-${tone}" href="${url}"><small>${number} / 06</small><i>${number}</i><div><h2>${title}</h2><p>${text}</p><b>Explorar →</b></div></a>`).join("")}</div><footer><div><span>Compártelo</span><h2>Que otra persona descubra Atlas.</h2><p>Envía una tarjeta visual por WhatsApp o abre el QR a pantalla completa.</p></div><button class="primary-button" data-action="share-public-app">Compartir Atlas</button><button class="secondary-button" data-action="open-qr">Ver QR</button></footer></section>`;
  }
  function renderGeneralExam(route) {
    const guides=window.ATLAS_EXAM_GUIDES?.guides||[];
    if(route.segments[1]==="general") return `<section class="page atlas-v7 v7-general-session"><header><a href="#/examen">Cerrar</a><span>Examen general · privado</span><h1>Haz silencio. Mira el día con Dios.</h1><p>No hay una puntuación ni hace falta contestar todo. Detente donde encuentres agradecimiento, dolor, perdón o una llamada concreta.</p></header><ol>${generalExamQuestions.map(([title,question],index)=>`<li><span>${String(index+1).padStart(2,"0")}</span><div><h2>${esc(title)}</h2><p>${esc(question)}</p><label><input type="checkbox"> Lo he mirado con sinceridad</label></div></li>`).join("")}</ol><footer><blockquote>Señor, gracias. Perdóname. Ayúdame a recomenzar mañana contigo.</blockquote><a class="primary-button" href="#/rezar">Terminar en paz</a><a class="secondary-button" href="#/spiritual/confession">Preparar la confesión</a></footer></section>`;
    return `<section class="page atlas-v7 v7-general-exam"><header><a href="#/rezar">← Rezar</a><span>Examen general</span><h1>Mirar el día con verdad y con paz.</h1><p>Una ayuda sencilla para agradecer, pedir perdón y recomenzar. Tus respuestas no salen del dispositivo.</p></header><a class="v7-exam-start" href="#/examen/general"><b>Comenzar examen breve</b><span>Lo esencial · pocos minutos →</span></a><section>${guides.map(guide=>`<a href="#/examen/guide/${encodeURIComponent(guide.id)}"><small>${esc(guide.audience)}</small><h2>${esc(guide.shortTitle||guide.title)}</h2><p>${esc(guide.introduction)}</p><b>Abrir guía →</b></a>`).join("")}</section><a class="v7-confession-link" href="#/spiritual/confession"><b>Preparar la confesión</b><span>Estructura, fórmulas y dudas frecuentes →</span></a><p>Los recursos específicos para miembros se habilitan introduciendo el código OD en Mi Atlas.</p></section>`;
  }

  document.addEventListener("submit",async event=>{
    if(event.target.id==="v7-ask-form"){event.preventDefault();const q=new FormData(event.target).get("q")?.trim();if(q)location.hash=`/preguntar?q=${encodeURIComponent(q)}`;}
    if(event.target.id==="v7-prayer-form"){event.preventDefault();const q=new FormData(event.target).get("q")?.trim();if(!q)return;const meditation=A.data.libraryMap.get("meditacion-diaria"),prompt=`Ayúdame a convertir esto en una oración personal, sincera y dirigida a Dios. No me des una explicación: acompáñame a hablar con Él.\n\n${q}`;const opened=meditation?.notebookUrl?window.open(meditation.notebookUrl,"_blank","noopener"):null;await A.share.copy(prompt);A.appToast?.(opened?"Tu oración está copiada. Pégala en el cuaderno que se acaba de abrir.":"Tu oración está copiada.");}
  });
  document.addEventListener("click",async event=>{
    const prayerExample=event.target.closest("[data-prayer-example]");if(prayerExample){const field=document.querySelector('#v7-prayer-form textarea');if(field){field.value=prayerExample.dataset.prayerExample;field.focus();}}
    const notebook=event.target.closest("[data-architecture-notebook]");if(notebook){const prompt=notebook.dataset.architecturePrompt||"";await A.share.copy(prompt);A.appToast?.("Consulta copiada. Pégala al abrir el cuaderno.");if(notebook.dataset.architectureNotebook)window.open(notebook.dataset.architectureNotebook,"_blank","noopener");}
    const lock=event.target.closest("[data-lock-feature]");if(lock){A.storage.lockFeature(lock.dataset.lockFeature);location.hash=`/mi-atlas?locked=${Date.now()}`;A.appToast?.("Recursos OD bloqueados de nuevo en este dispositivo.");}
  });
  A.architecture={renderHome,renderLibrary,renderAsk,renderPrayer,renderLearning,renderOpusDei,renderMyAtlas,renderMore,renderDiscoverAtlas,renderGeneralExam};
})();
